{ config, lib, ... }:
let
  flakeConfig = config;

  adapterModule = { lib, ... }: {
    options.enable = lib.mkEnableOption "tmux-flake integration";
  };

  tmuxModule =
    { config, lib, pkgs, ... }:
    let
      cfg = config.rum.programs.tmux.flake;

      tmuxConf = pkgs.writeText "tmux.conf" ''
        # Generated by tmux-flake - do not edit.
        ${cfg.rc}
      '';

      tmuxSessionWrapper = pkgs.writeShellApplication {
        name = "tmux-session-wrapper";
        runtimeInputs = [ pkgs.coreutils pkgs.util-linux ];
        text = ''
          unset TMUX TMUX_TMPDIR

          exec "$@"
        '';
      };

      startScript = pkgs.writeShellApplication {
        name = "tmux-start-server";
        runtimeInputs = [ pkgs.tmux ];
        text = ''
          tmux_config="$HOME/.config/tmux/tmux.conf"
          printf 'tmux-start-server: starting tmux server\n'
          tmux -f "$tmux_config" start-server
        '';
      };

      restoreScript = pkgs.writeShellApplication {
        name = "tmux-restore-sessions";
        runtimeInputs = with pkgs; [
          tmux
          coreutils
          bash
          gawk
          gnugrep
          gnused
          gnutar
          inetutils
          gzip
        ];
        text = ''
          restore_script="${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/scripts/restore.sh"

          if tmux has-session 2>/dev/null; then
            printf 'tmux-restore-sessions: sessions already exist\n'
            exit 0
          fi

          tmux -f "$HOME/.config/tmux/tmux.conf" new-session -Ad -s 0
          socket="$(tmux display-message -p '#{socket_path}')"
          export TMUX="$socket,0,0"

          if [ -x "$restore_script" ]; then
            printf 'tmux-restore-sessions: restoring saved sessions\n'
            if "$restore_script"; then
              printf 'tmux-restore-sessions: restore completed\n'
            else
              printf 'tmux-restore-sessions: restore failed\n'
            fi
          else
            printf 'tmux-restore-sessions: script unavailable: %s\n' "$restore_script"
          fi
        '';
      };

      defaultScript = pkgs.writeShellApplication {
        name = "tmux-ensure-default";
        runtimeInputs = [ pkgs.tmux ];
        text = ''
          if ! tmux has-session 2>/dev/null; then
            printf 'tmux-ensure-default: creating fallback session\n'
            tmux -f "$HOME/.config/tmux/tmux.conf" new-session -Ad -s default
          fi
        '';
      };
    in
    {
      options.rum.programs.tmux.flake = lib.mkOption {
        type = lib.types.submoduleWith {
          modules = flakeConfig.tmux.modules ++ [ adapterModule ];
          specialArgs = { inherit pkgs; };
        };
        default = { };
        description = "tmux-flake configuration rendered into Hjem.";
      };

      config = lib.mkIf cfg.enable {
        packages = cfg.packages ++ lib.optional cfg.persistence.enable tmuxSessionWrapper;
        files.".config/tmux/tmux.conf".source = tmuxConf;

        systemd.services = lib.mkIf cfg.persistence.enable {
          tmux-sessions-start = {
            description = "Start tmux server";
            wantedBy = [ "default.target" ];
            serviceConfig = {
              Type = "oneshot";
              RemainAfterExit = true;
              ExecStart = "${lib.getExe tmuxSessionWrapper} ${lib.getExe startScript}";
            };
          };

          tmux-sessions-restore = {
            description = "Restore saved tmux sessions";
            wantedBy = [ "default.target" ];
            requires = [ "tmux-sessions-start.service" ];
            after = [ "tmux-sessions-start.service" ];
            serviceConfig = {
              Type = "oneshot";
              RemainAfterExit = true;
              ExecStart = "${lib.getExe tmuxSessionWrapper} ${lib.getExe restoreScript}";
            };
          };

          tmux-sessions-default = {
            description = "Create the default tmux session when needed";
            wantedBy = [ "default.target" ];
            requires = [ "tmux-sessions-restore.service" ];
            after = [ "tmux-sessions-restore.service" ];
            serviceConfig = {
              Type = "oneshot";
              RemainAfterExit = true;
              ExecStart = "${lib.getExe tmuxSessionWrapper} ${lib.getExe defaultScript}";
            };
          };
        };
      };
    };
in
{
  flake.hjemModules.default = {
    imports = [ tmuxModule ];
  };
}
