{ config, lib, ... }:
let
  baseModules = [
    ./+wrapper/modules/options.nix
    ./+wrapper/modules/mouse.nix
    ./+wrapper/modules/mode.nix
    ./+wrapper/modules/windows.nix
    ./+wrapper/modules/history.nix
    ./+wrapper/modules/prefix.nix
    ./+wrapper/modules/extended-keys.nix
    ./+wrapper/modules/persistence.nix
  ];

  tmuxModule =
    { config, pkgs, ... }:
    let
      zshIntegration = ''
        _tmux_session_name() {
          local name="''${1:-default}"

          name="''${name//[^[:alnum:]_-]/-}"
          print -r -- "''${name:-default}"
        }

        alias t='tmux'
        alias tl='tmux list-sessions'
        alias tks='tmux kill-server'

        tj() {
          local session="$(_tmux_session_name "$1")"

          if [ -n "$TMUX" ]; then
            if ! tmux has-session -t "=$session" 2>/dev/null; then
              tmux new-session -d -s "$session" -c "$PWD" || return
            fi
            tmux switch-client -t "=$session"
          elif tmux has-session -t "=$session" 2>/dev/null; then
            tmux attach-session -t "=$session"
          else
            tmux new-session -s "$session" -c "$PWD"
          fi
        }

        tjh() {
          tj "$(basename "$PWD")"
        }

        tk() {
          local session

          if [ -z "$1" ]; then
            print -u2 -- 'usage: tk <session>'
            return 2
          fi

          session="$(_tmux_session_name "$1")"
          tmux kill-session -t "=$session"
        }

        _tmux_session_names() {
          tmux list-sessions -F '#S' 2>/dev/null
        }

        _tmux_session_complete() {
          compadd -- $(_tmux_session_names)
        }

        if (( $+functions[compdef] )); then
          compdef _tmux_session_complete tj
          compdef _tmux_session_complete tk
        fi
      '';

      tmuxConf = pkgs.writeText "tmux.conf" ''
        # Generated by tmux-flake - do not edit.
        ${config.tmux.initConfig}
      '';

      tmuxSessionWrapper = pkgs.writeShellApplication {
        name = "tmux-session-wrapper";
        runtimeInputs = [ pkgs.coreutils pkgs.util-linux ];
        text = ''
          unset TMUX TMUX_TMPDIR

          exec "$@"
        '';
      };

      startScript = pkgs.writeShellApplication {
        name = "tmux-start-server";
        runtimeInputs = [ pkgs.tmux ];
        text = ''
          tmux_config="$HOME/.config/tmux/tmux.conf"
          printf 'tmux-start-server: starting tmux server\n'
          tmux -f "$tmux_config" start-server
        '';
      };

      restoreScript = pkgs.writeShellApplication {
        name = "tmux-restore-sessions";
        runtimeInputs = with pkgs; [
          tmux
          coreutils
          bash
          gawk
          gnugrep
          gnused
          gnutar
          inetutils
          gzip
        ];
        text = ''
          restore_script="${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/scripts/restore.sh"

          if tmux has-session 2>/dev/null; then
            printf 'tmux-restore-sessions: sessions already exist\n'
            exit 0
          fi

          tmux -f "$HOME/.config/tmux/tmux.conf" new-session -Ad -s 0
          socket="$(tmux display-message -p '#{socket_path}')"
          export TMUX="$socket,0,0"

          if [ -x "$restore_script" ]; then
            printf 'tmux-restore-sessions: restoring saved sessions\n'
            if "$restore_script"; then
              printf 'tmux-restore-sessions: restore completed\n'
            else
              printf 'tmux-restore-sessions: restore failed\n'
            fi
          else
            printf 'tmux-restore-sessions: script unavailable: %s\n' "$restore_script"
          fi
        '';
      };

      defaultScript = pkgs.writeShellApplication {
        name = "tmux-ensure-default";
        runtimeInputs = [ pkgs.tmux ];
        text = ''
          if ! tmux has-session 2>/dev/null; then
            printf 'tmux-ensure-default: creating fallback session\n'
            tmux -f "$HOME/.config/tmux/tmux.conf" new-session -Ad -s default
          fi
        '';
      };
    in
    {
      imports = baseModules;

      options.integrations.zsh.enable = lib.mkEnableOption "tmux Zsh integration";

      config = {
        packages = config.tmux.packages ++ lib.optional config.tmux.persistence.enable tmuxSessionWrapper;
        files.".config/tmux/tmux.conf".source = tmuxConf;
        user.linger = lib.mkIf config.tmux.persistence.enable true;
        rum.programs.zsh.initConfig = lib.mkIf config.integrations.zsh.enable (lib.mkAfter zshIntegration);

        systemd.services = lib.mkIf config.tmux.persistence.enable {
          tmux-sessions-start = {
            description = "Start tmux server";
            wantedBy = [ "default.target" ];
            serviceConfig = {
              Type = "oneshot";
              RemainAfterExit = true;
              ExecStart = "${lib.getExe tmuxSessionWrapper} ${lib.getExe startScript}";
            };
          };

          tmux-sessions-restore = {
            description = "Restore saved tmux sessions";
            wantedBy = [ "default.target" ];
            requires = [ "tmux-sessions-start.service" ];
            after = [ "tmux-sessions-start.service" ];
            serviceConfig = {
              Type = "oneshot";
              RemainAfterExit = true;
              ExecStart = "${lib.getExe tmuxSessionWrapper} ${lib.getExe restoreScript}";
            };
          };

          tmux-sessions-default = {
            description = "Create the default tmux session when needed";
            wantedBy = [ "default.target" ];
            requires = [ "tmux-sessions-restore.service" ];
            after = [ "tmux-sessions-restore.service" ];
            serviceConfig = {
              Type = "oneshot";
              RemainAfterExit = true;
              ExecStart = "${lib.getExe tmuxSessionWrapper} ${lib.getExe defaultScript}";
            };
          };
        };
      };
    };
in
{
  flake.hjemModules.default = {
    imports = [ tmuxModule ];
  };
}
